apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-db
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 512Mi
  storageClassName: gp2
